app = "sceneshare"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  DJANGO_SETTINGS_MODULE = "sceneshare.settings"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    force_https = true

  [[services.ports]]
    port = 443

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
