# Generated by Django 4.2.24 on 2025-10-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'community',
            (
                '0002_alter_reviewlike_created_at_alter_reviewlike_review_and_'
                'more'
            ),
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
